// <auto-generated />
using System;
using CartService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CartService.Migrations
{
    [DbContext(typeof(CartDbContext))]
    [Migration("20260905151256_UserSeed")]
    partial class UserSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CartService.Data.Model.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("CartService.Data.Model.CartItem", b =>
                {
                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("CartService.Data.Model.IdentityServiceModel.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            Email = "flukas@example.com",
                            FirstName = "Filip",
                            LastName = "Lukas",
                            Username = "flukas"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            Email = "aantic@example.com",
                            FirstName = "Ante",
                            LastName = "Antic",
                            Username = "aantic"
                        });
                });

            modelBuilder.Entity("CartService.Data.Model.InventoryServiceModel.ItemQuantity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("ItemQuantities");
                });

            modelBuilder.Entity("CartService.Data.Model.ProductCatalogServiceModel.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("Items", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CartService.Data.Model.ProductCatalogServiceModel.Ball", b =>
                {
                    b.HasBaseType("CartService.Data.Model.ProductCatalogServiceModel.Item");

                    b.Property<double>("Diameter")
                        .HasColumnType("float");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Balls", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            Description = "Regulation tennis ball",
                            Name = "Championship Tennis Ball",
                            Price = 2.99m,
                            Diameter = 6.7000000000000002,
                            Material = "Rubber/Felt"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            Description = "Practice-grade tennis ball",
                            Name = "Practice Tennis Ball",
                            Price = 1.99m,
                            Diameter = 6.7000000000000002,
                            Material = "Rubber/Felt"
                        });
                });

            modelBuilder.Entity("CartService.Data.Model.ProductCatalogServiceModel.Racket", b =>
                {
                    b.HasBaseType("CartService.Data.Model.ProductCatalogServiceModel.Item");

                    b.Property<string>("GripSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HeadSize")
                        .HasColumnType("float");

                    b.ToTable("Rackets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            Description = "Professional tennis racket",
                            Name = "Pro Racket",
                            Price = 149.99m,
                            GripSize = "L2",
                            HeadSize = 645.0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            Description = "Lightweight racket for juniors",
                            Name = "Junior Racket",
                            Price = 59.99m,
                            GripSize = "L0",
                            HeadSize = 600.0
                        });
                });

            modelBuilder.Entity("CartService.Data.Model.ProductCatalogServiceModel.Shoes", b =>
                {
                    b.HasBaseType("CartService.Data.Model.ProductCatalogServiceModel.Item");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.ToTable("Shoes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            Description = "Tennis court shoes",
                            Name = "Court Runner",
                            Price = 89.99m,
                            Brand = "SportX",
                            Size = 42
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            Description = "High-grip tennis shoes",
                            Name = "Grip Master",
                            Price = 99.99m,
                            Brand = "SportX",
                            Size = 43
                        });
                });

            modelBuilder.Entity("CartService.Data.Model.Cart", b =>
                {
                    b.HasOne("CartService.Data.Model.IdentityServiceModel.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CartService.Data.Model.CartItem", b =>
                {
                    b.HasOne("CartService.Data.Model.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartService.Data.Model.ProductCatalogServiceModel.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("CartService.Data.Model.InventoryServiceModel.ItemQuantity", b =>
                {
                    b.HasOne("CartService.Data.Model.ProductCatalogServiceModel.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CartService.Data.Model.ProductCatalogServiceModel.Item", b =>
                {
                    b.HasOne("CartService.Data.Model.Cart", null)
                        .WithMany("Items")
                        .HasForeignKey("CartId");
                });

            modelBuilder.Entity("CartService.Data.Model.ProductCatalogServiceModel.Ball", b =>
                {
                    b.HasOne("CartService.Data.Model.ProductCatalogServiceModel.Item", null)
                        .WithOne()
                        .HasForeignKey("CartService.Data.Model.ProductCatalogServiceModel.Ball", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CartService.Data.Model.ProductCatalogServiceModel.Racket", b =>
                {
                    b.HasOne("CartService.Data.Model.ProductCatalogServiceModel.Item", null)
                        .WithOne()
                        .HasForeignKey("CartService.Data.Model.ProductCatalogServiceModel.Racket", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CartService.Data.Model.ProductCatalogServiceModel.Shoes", b =>
                {
                    b.HasOne("CartService.Data.Model.ProductCatalogServiceModel.Item", null)
                        .WithOne()
                        .HasForeignKey("CartService.Data.Model.ProductCatalogServiceModel.Shoes", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CartService.Data.Model.Cart", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
